apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 10000000"]
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
