# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  # base64 secrest:
  # echo -n 'myvalue' |base64
  DB_Host: bXlzcWw=
  DB_User: cm9vdA==
  DB_Password: cGFzc2Q=
